---
version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 20
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: 100
  identical-code:
    config:
      threshold: 20
exclude_paths:
  - coverage/**/*
  - docs/**/*
  - es/**/*
  - lib/**/*
  - node_modules/**/*
  - test/**/*
